#! /bin/sh
# (c) 2019 - LGPL - BeePerNet


if [ ! -r "/dev/shm/MPL3115-pressure" ]
then
	echo "# Cannot read pressure"
	exit 1
fi


if [ "$1" = "config" ]
then
        cat <<EOF
graph_title Pressure
graph_category sensors
graph_vlabel Pa
press0.label Ambiant Pressure
EOF
        exit 0
fi

# values
TEMP_MILLI_C=$(cat /dev/shm/MPL3115-pressure)

echo "press0.value $(echo "$TEMP_MILLI_C" | awk '{printf("%0.3f", $1)}')"

exit 0
